/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Hotel Name]
      ,[Citry , Country]
      ,[Reservation ID]
      ,[Arrival Date]
      ,[Departure Date]
      ,[Rooms Type]
      ,[Customer Name]
      ,[Phone Number]
      ,[National ID]
      ,[Gender]
      ,[Adults]
      ,[Children]
  FROM [Travel_agency].[dbo].[Add_Hotels]